### ISSUE TITLE
Create generic PR template

### ISSUE THREAD

**Issue by abbyoung** [USSF-ORBIT/ussf-portal#23]
Create simple PR template for initial use in our repos.

Includes:
* Description
* Issue fixed
* Review Notes

Open Q: Should we store in our meta repo for now, and copy to repos as needed? I realize they're not all created yet. cc @suzubara

**Comment by abbyoung** [comment]
"You can add default community health files to the root of a public repository called .github that is owned by an organization or user account."

Do we want to do this @suzubara, or keep it per repo?

**Comment by suzubara** [comment]
Ohh that sounds really useful! Let's do the .github repo!
